### ISSUE TITLE
Numba dependency conflict

### ISSUE THREAD

**Issue by Athanaseus** [ratt-ru/QuartiCal#157]
**Describe the bug**
`numba` 0.55.1 has requirement `numpy`<1.22,>=1.18, but you'll have `numpy` 1.22.4 which is incompatible.
This happens with the main branch and latest release on pypi.

**To Reproduce**
`pip install quartical.`

**Version**
Ubuntu-20.04
Quartical-0.1.1
Python3.8

**Comment by JSKenyon** [comment]
Yeah - I don't know why setuptools doesn't resolve this correctly. The workaround for now is to just uninstall Numpy and install the last version supported by numba.

**Comment by Athanaseus** [comment]
Thanks @JSKenyon  that's exactly what i did.
I think numpy listed in the setup requirements is installed first,
then when numba is installed it finds the latest numpy already.

**Comment by JSKenyon** [comment]
This should now be resolved - the latest `numba` release supports numpy==1.22.4.
