### ISSUE TITLE
Python 3.10 tests currently failing

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/QuartiCal#174]
**Describe the bug**
Tests fail on Python 3.10 due to a binary incompatibility between the `numpy` version required by `numba` (currently < 1.23) and the numpy version used to build `python-casacore`. This cannot be resolved without a version of `python-casacore` which works with `numpy < 1.23` or a version of `numba` which supports `numpy>=1.23`. Waiting for a `numba` release is the simpler approach but way take a few months.  

**To Reproduce**
Simply run the tests under Python 3.10.

**Expected behavior**
QuartiCal should work under Python 3.10.

**Comment by bennahugo** [comment]
Yea you will probably need a reasonably new boost installed on the system

**Comment by JSKenyon** [comment]
This is on 20.04. I still think I am justified in whining as this basically renders QuartiCal uninstallable under Python 3.10 without fiddling. I suspect that 20.04 doesn't have a sufficiently recent boost and installing that manually doesn't really resolve the issue. I have opened https://github.com/casacore/python-casacore/issues/235 as I believe that there should either be a final 3.4 release which supports 3.10 or the 3.5 release should work with the first version of numpy to support Python 3.10.

**Comment by JSKenyon** [comment]
This has been fixed upstream.

**Comment by bennahugo** [comment]
Yup agreed.

Boost is only bundled for the python that is natively bundled with your
version - here 3.8 in other words.

It may help to upgrade to Ubuntu 22.04 which ships 3.10 as the default
