### ISSUE TITLE
Quartical not launching 

### ISSUE THREAD

**Issue by phetogoportia** [ratt-ru/QuartiCal#191]
I am trying to run QuartiCal however I get this error message instead:  

2022-08-23 11:03:16.195 | INFO     | quartical.config.parser:parse_inputs:109 - User defined config file: user_config.yaml
2022-08-23 11:03:16.222 | ERROR    | __main__:<module>:33 - An error has been caught in function '<module>', process 'MainProcess' (3640873), thread 'MainThread' (139844306384704):
Traceback (most recent call last):

> File "/home/phetogo/venv/quartica/bin/goquartical", line 33, in <module>
    sys.exit(load_entry_point('quartical', 'console_scripts', 'goquartical')())
    │   │    └ <function importlib_load_entry_point at 0x7f3009fd61f0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/home/phetogo/Software/QuartiCal/quartical/executor.py", line 32, in execute
    _execute(stack)
    │        └ <contextlib.ExitStack object at 0x7f3009c91f40>
    └ <function _execute at 0x7f2f406238b0>

  File "/home/phetogo/Software/QuartiCal/quartical/executor.py", line 41, in _execute
    opts = parser.parse_inputs()
           │      └ <function parse_inputs at 0x7f2f48afb160>
           └ <module 'quartical.config.parser' from '/home/phetogo/Software/QuartiCal/quartical/config/parser.py'>

  File "/home/phetogo/Software/QuartiCal/quartical/config/parser.py", line 115, in parse_inputs
    yml_config = [oc.load(file) for file in config_files]
                  │  │    │         │       └ ['user_config.yaml']
                  │  │    │         └ 'user_config.yaml'
                  │  │    └ 'user_config.yaml'
                  │  └ <staticmethod object at 0x7f2fad05ad90>
                  └ <class 'omegaconf.omegaconf.OmegaConf'>

  File "/home/phetogo/Software/QuartiCal/quartical/config/parser.py", line 115, in <listcomp>
    yml_config = [oc.load(file) for file in config_files]
                  │  │    │         └ 'user_config.yaml'
                  │  │    └ 'user_config.yaml'
                  │  └ <staticmethod object at 0x7f2fad05ad90>
                  └ <class 'omegaconf.omegaconf.OmegaConf'>

  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 188, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
          │    │    │         └ <function get_yaml_loader at 0x7f2fad082b80>
          │    │    └ <_io.TextIOWrapper name='/home/phetogo/new_project/CGCG021-063/user_config.yaml' mode='r' encoding='utf-8'>
          │    └ <function load at 0x7f30093d61f0>
          └ <module 'yaml' from '/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/__init__.py'>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7f30095b3dc0>
           └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7f30094338b0>
           └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7f3009433940>
               └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7f30094339d0>
           └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7f3009433b80>
           └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7f30095b5040>
              └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
    │    └ None
    └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
  File "/home/phetogo/venv/quartica/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7f2f40610610>]
          │                                            └ <omegaconf._utils.get_yaml_loader.<locals>.OmegaConfLoader object at 0x7f2f40610640>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/phetogo/new_project/CGCG021-063/user_config.yaml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/phetogo/new_project/CGCG021-063/user_config.yaml", line 68, column 2

**Comment by JSKenyon** [comment]
Hi @phetogoportia! Could you please upload your config file? Looking at the error message, it looks like there is a mistake in `user_config.yaml`. The important line in the error is: `expected , but found ''`.

**Comment by phetogoportia** [comment]
[config.txt](https://github.com/ratt-ru/QuartiCal/files/9401423/config.txt)

**Comment by JSKenyon** [comment]
The issue is whitespace - yaml is whitespaced, so every space/tab is important. The `K` section of your config has a space in front of it. Removing it will make it work. I have tested it.

You will also run into a second error because the `reference_antenna` field currently contains no value. This must be set (the default is to use 0).

**Comment by landmanbester** [comment]
Why don't you use goquartical-config to produce your config file @phetogoportia? That will save you from running into issues like these. Try running
```
$ goquartical-config name_of_config_file.yaml
```
