### ISSUE TITLE
Separate delay and f-slope solvers

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/QuartiCal#192]
As discussed, it would be useful to have separate delay (i.e. pure slope) and f-slope (slope + offset) solvers. The main issue with using f-slope during 1GC is that the phase of G get's absorbed into the offset making it difficult to smoothly interpolate over scan boundaries

**Comment by JSKenyon** [comment]
Addressed in #233. As mentioned in the PR, I have resolved to use `delay` and `pure_delay` as the naming convention for now. A `pure_delay` term will not include a phase offset.
