### ISSUE TITLE
Add a feature to disable logger to print in terminal

### ISSUE THREAD

**Issue by devojyoti96** [ratt-ru/QuartiCal#214]
**Describe the problem that the feature should address**
Add a feature to disable logger to print in terminal, but the logs are kepe in log file as it is.

**Describe the solution you'd like**
I request to add a keyword  in input using which user can stop printing the logs in terminal. I am using it in a pipeline, and I like to keep the logs in log files but do not want to print them in terminal.

**Comment by JSKenyon** [comment]
Added in #219. Can be controlled by setting `output.log_to_terminal`.
