### ISSUE TITLE
Unity model option

### ISSUE THREAD

**Issue by landmanbester** [ratt-ru/QuartiCal#222]
**Describe the problem that the feature should address**
When calibrating the secondary we often assume it is a unity point source at the phase center which translates to unity visibilities on the diagonals. It would be great if we didn't have to populate the MODEL_DATA column when this is the case. Note Quartical currently falls over if input_model.recipe is None 

**Describe the solution you'd like**
There should be a way to tell QuartiCal to treat the model as unity  

**Describe alternatives you've considered**
Populating the MODEL_DATA column with ones on the diagonal works but it is wasteful

**Comment by bennahugo** [comment]
I think this should be the default (good enough for phase and delays) if no
model is available.

**Comment by JSKenyon** [comment]
Please let me know if this functionality doesn't work as expected.
