### ISSUE TITLE
tigger lsm error in DDE

### ISSUE THREAD

**Issue by Sinenhlanhla** [ratt-ru/QuartiCal#241]
I am trying 3GC using a tigger skymodel with a few sources tagged. I am getting the error below.

2023-04-03 17:19:46 | ERROR | goquartical:<module> | An error has been caught in function '<module>', process 'MainProcess' (33259), thread 'MainThread' (140324414400320):
Traceback (most recent call last):

> File "/home/oem/venv/bin/goquartical", line 33, in <module>
    sys.exit(load_entry_point('quartical', 'console_scripts', 'goquartical')())
    │   │    └ <function importlib_load_entry_point at 0x7f9fd1bc9f70>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "/mnt/12tb/QuartiCal/quartical/executor.py", line 28, in execute
    _execute(stack)
    │        └ <contextlib.ExitStack object at 0x7f9fd1c1a700>
    └ <function _execute at 0x7f9f8ddd4f70>

  File "/mnt/12tb/QuartiCal/quartical/executor.py", line 111, in _execute
    data_xds_list = add_model_graph(
                    └ <function add_model_graph at 0x7f9f910958b0>

  File "/mnt/12tb/QuartiCal/quartical/data_handling/model_handler.py", line 40, in add_model_graph
    predict_schemes = predict(data_xds_list,
                      │       └ [<xarray.Dataset>
                      │         Dimensions:     (row: 232960, chan: 1024, uvw: 3, corr: 2, ant: 64)
                      │         Coordinates:
                      │             ROWID       (row) int3...
                      └ <function predict at 0x7f9f90168f70>

  File "/mnt/12tb/QuartiCal/quartical/data_handling/predict.py", line 378, in predict
    sky_model_dict = parse_sky_models(model_vis_recipe.ingredients.sky_models)
                     │                │                │           └ {sky_model_nt(name='j0329.lsm.html', tags=('dE',))}
                     │                │                └ Ingredients(model_columns=set(), sky_models={sky_model_nt(name='j0329.lsm.html', tags=('dE',))})
                     │                └ Recipe(ingredients=Ingredients(model_columns=set(), sky_models={sky_model_nt(name='j0329.lsm.html', tags=('dE',))}), instruct...
                     └ <function parse_sky_models at 0x7f9f91095b80>

  File "/mnt/12tb/QuartiCal/quartical/data_handling/predict.py", line 113, in parse_sky_models
    msg = "".join(

  File "/mnt/12tb/QuartiCal/quartical/data_handling/predict.py", line 114, in <genexpr>
    "\n  {:<8}: {} point source/s, {} Gaussian source/s".format(

TypeError: unsupported format string passed to NoneType.__format__

**Comment by JSKenyon** [comment]
Sorry to hear that you have run into a bug! Could you please upload/make the sky model in question available to me along with your QuaritCal config file/command/log?

**Comment by Sinenhlanhla** [comment]
I've attached both files.
[j0329_qcal.zip](https://github.com/ratt-ru/QuartiCal/files/11145919/j0329_qcal.zip)

**Comment by JSKenyon** [comment]
Ok - I can reproduce on an arbitrary dataset. Will sort out a fix asap.

**Comment by Sinenhlanhla** [comment]
Thanks

**Comment by JSKenyon** [comment]
Ok, I have made a PR with a fix. Need the tests to pass. Are you using the `stimelation` branch?

**Comment by Sinenhlanhla** [comment]
Uhmm, I'm currently using the development mode (which has polcal).

**Comment by JSKenyon** [comment]
If you are using the `main` branch installed with `-e`, then the fixes will be available shortly. Just need the tests to finish passing.

**Comment by Sinenhlanhla** [comment]
Yes, I'm using the `main` branch. Okay, great!

**Comment by JSKenyon** [comment]
OK, if you pull `main` the problem should be fixed. Let me know if you still encounter problems. :-)

**Comment by Sinenhlanhla** [comment]
Okay, will do. Thanks.

**Comment by JSKenyon** [comment]
Actually, can you please update your `codex-africanus`? I think that this has already been fixed.

**Comment by Sinenhlanhla** [comment]
Okay, updating seems to have done the trick. Thanks.

**Comment by JSKenyon** [comment]
Awesome!
