### ISSUE TITLE
Find-replace np.bool -> np.bool_ and np.int -> np.int_

### ISSUE THREAD

**Issue by Joshuaalbert** [ratt-ru/QuartiCal#254]
**Describe the bug**
Since numpy 1.24.0 np.bool and np.int have been removed, and you get an error when trying to use np.bool. Also np.int. Simple find and replace should do the trick.

You get this,
```bash
AttributeError: module 'numpy' has no attribute 'bool'
```

**To Reproduce**
Run any code that calls predict with numpy 1.24.0+

**Comment by JSKenyon** [comment]
There were only two instances of `np.bool` in QuartiCal and zero of `np.int`. I have changed the `np.bool` cases on my current branch, so they will end up in the `v0.2.0-dev` branch. If the problem stems from the predict, the offending code may be inside `codex-africanus`. @sjperkins can you comment?

**Comment by Joshuaalbert** [comment]
I think I only saw in this repo.

**Comment by JSKenyon** [comment]
Fixed on `v0.2.0-dev`.
