### ISSUE TITLE
[Question] Is there a requirement that each 'direction' represent a relatively compact sky model?

### ISSUE THREAD

**Issue by Joshuaalbert** [ratt-ru/QuartiCal#257]
I am just getting to using Quartical's DD calibration, to explore DSA in response to DD errors. I notice that the syntax is flexible for specifying DD `input_model.recipe`. 

Questions:
1. Is it right to call each sky model in the the `recipe` a 'direction'? Couldn't each 'direction' actually correspond to a sky-model that covers the entire field of view, e.g. broken up into bright and faint sets of sources?
2. Or, perhaps there is a requirement that each 'direction' represent a small part of the image, e.g use an estimate of the isoplanatic patch size. In this case, is there interpolation happening between 'directions' onto individual sources? I suspect not as this would require coordination between directions being solved.

**Comment by JSKenyon** [comment]
>     1. Is it right to call each sky model in the the `recipe` a 'direction'? Couldn't each 'direction' actually correspond to a sky-model that covers the entire field of view, e.g. broken up into bright and faint sets of sources?

The elements of a `recipe` are `ingredients`. A single `ingredient` may produce one (e.g. a single MS column) or more (e.g. a tagged tigger.lsm.html file with multiple clusters) directions, where a direction is simply shorthand for the visibility associated with some component of the field. You could absolutely use this mechanism to partition the sky into bright and faint sources. QuartiCal is incredibly flexible in this regard. Please let me know if you need further clarification.

>     2. Or, perhaps there is a requirement that each 'direction' represent a small part of the image, e.g use an estimate of the isoplanatic patch size. In this case, is there interpolation happening between 'directions' onto individual sources? I suspect not as this would require coordination between directions being solved.

There is absolutely no requirement on the `ingredients` or produced `directions`. They can correspond to a single source or the entire field. At present there is no smoothing/interpolation of the direction dependent solutions inside the solver i.e. no communication between directions, beyond the fact that they are calibrated simultaneously.
