### ISSUE TITLE
pandas.errors.InvalidIndexError

### ISSUE THREAD

**Issue by bngcebetsha** [ratt-ru/QuartiCal#336]
**Describe the bug**
I have a calibrated dataset flagged around 63% from MeerKAT, the output is also on the markdown file attached. I need to correct for the phase on the target field as well as the phase slope.

[quartical_error_proxima_cen_target.md](https://github.com/user-attachments/files/15816294/quartical_error_proxima_cen_target.md)

**To Reproduce**
I have attached both commands I ran to derive and apply the gains on the markdown file above

**Expected behavior**
I expect for the derived gain solutions to be applied to the relevant data columns on the measurement set. Such that when I image the corrected data I get improved images. 

**Version**
`quartical==0.2.0`

**Comment by bngcebetsha** [comment]
> Hmm, that looks very suspicious. I would definitely recommend updating to the latest version of QuartiCal.
> 
> My instinct is that your gain solutions may not have been written correctly. Are you running QuartiCal locally or somewhere I have access to (Rhodes/CHPC boxes)? If so, I can take a quick look.

I might agree the calibration step ended with a `killed` - I am running this on `young` on this path `/home/bngcebetsha/cal_quartical`

**Comment by JSKenyon** [comment]
Kill your run please - your config is completely swamping memory.

**Comment by bngcebetsha** [comment]
> Kill your run please - your config is completely swamping memory.

we have `DynSpecMS` to thank for this. Ok thanks @JSKenyon . I will try out your suggestions and update/close the issue when done.

**Comment by JSKenyon** [comment]
> > Kill your run please - your config is completely swamping memory.
> 
> we have `DynSpecMS` to thank for this. Ok thanks @JSKenyon . I will try out your suggestions and update/close the issue when done.

Great! Sorry - I was struggling to communicate with young so I was just guessing that it was QC to blame. But yeah, swap was full and that usually means game over. Hitting swap is bad enough.

**Comment by bngcebetsha** [comment]
> > > Kill your run please - your config is completely swamping memory.
> > 
> > 
> > we have `DynSpecMS` to thank for this. Ok thanks @JSKenyon . I will try out your suggestions and update/close the issue when done.
> 
> Great! Sorry - I was struggling to communicate with young so I was just guessing that it was QC to blame. But yeah, swap was full and that usually means game over. Hitting swap is bad enough.

In case you know how to help with this too - I am unable to log in now. I am guessing its the memory issue. I need to kill all my current processes and free up memory that `DynSpecMS` is hogging like this;
```sh
rm -fr /dev/shm/*
```
If it all you may please hep with that since I cannot login anymore.
