### ISSUE TITLE
Solver Flagging Everything

### ISSUE THREAD

**Issue by AKHughes1994** [ratt-ru/QuartiCal#343]
Hi, 

I am running QuartiCal (version 0.2.2) on some VLA data. 

For some context on the observations, the VLA data was sequentially observed at X (4-8 GHz) and then C (8-12 GHz) bands (3-bit samplers). As a result, in both bands, the observations are broken into two scans, each with the same number of frequency channels. Given that the observations are not simultaneous (and my target varies), I'm imaging the C and X bands separately. 

Now, I am trying to self-calibrate with QuartiCal. The non-self-calibrated images are dominated (in both bands) by my ~10 mJy point-like targets near the phase centre with an rms of ~10 uJy/beam (i.e., SNR ~ 1000). I've attached a reference screenshot. 
![image](https://github.com/user-attachments/assets/ae5a1a91-1269-4413-b177-ca9f5e54d621)

Now, when I try to self-calibrate X-band, there are no issues, and image quality is improved; below is the terminal output from the successful run:

![Screenshot from 2024-10-22 16-15-09](https://github.com/user-attachments/assets/659c2eba-acb0-4fd4-9bfc-4df653183e72)

However, when I try to do it with C-band, it's failing: 

![Screenshot from 2024-10-22 16-31-10](https://github.com/user-attachments/assets/9349a2cc-10fd-4656-b0bc-2f6238616cf5)

Despite using the same parset (attached but converted to .txt) and the same call, the only exception is changing the input ms.

`goquartical ../quartical_files/Phase_Selfcal.yaml input_ms.path={msfile}`

This comment may have been more suited for a discussion as I'm not exactly sure why it's failing (i.e., if it's a bug or not), nor where to look for why. Moreover, these observations are multi-epoch, so I have the same observing block take ~ 1 month later, and all of these scripts work without issue. So something is going on with this block in particular (and I'm hoping it's just something silly on my end)

[Phase_Selfcal.txt](https://github.com/user-attachments/files/17478956/Phase_Selfcal.txt)

**Comment by JSKenyon** [comment]
Hi @AKHughes1994 - that does seem odd. Are you absolutely certain the QuartiCal is the root cause of the 100% flagging? I ask because the CHISQ output is `nan -> nan`. This typically means that the data was already fully flagged in the input. As an experiment, you can try and revert to your previous flags and then run QuartiCal with `output.flags=false`. That will disable QuartiCal's ability to update the FLAG column. You can also run `goquartical-summary path/to/ms path/to/summary/folder` before and after to get an idea of what changed.

**Comment by AKHughes1994** [comment]
Hi @JSKenyon, 

I've triple-checked. Turning the `output.flags=false` prevents the flagging but (effectively) copies the DATA column to the CORRECTED_DATA column, which is expected as QC wants to flag everything. 

I've imaged the QC-corrected data, and it does look the same as the uncorrected data. 

The only thing I can think of is, for whatever reason, there is some weird interplay between QC and the ms file as I used CASA's `mstransform` to collapse the multiple VLA SPWs into a single SPW (this was to use WSCLEAN snapshot imaging, as without it the time intervals become funky). 

I'll check if QC works on the unchanged, multi-spw ms file and update the ticket. I've also attached the summary file, so if you have any ideas, let me know! Thanks for the speedy reply. 
[QC_flags_on_summary.txt](https://github.com/user-attachments/files/17487720/QC_flags_on_summary.txt)

**Comment by JSKenyon** [comment]
Have you checked the contents of MODEL_DATA?

**Comment by AKHughes1994** [comment]
Here's a plot of the C-band model (amplitudes): 

![image](https://github.com/user-attachments/assets/0ef5bdf8-e354-41ae-9f3d-40d146c77d13)

For reference, here are the X-band model (amplitudes)

![image](https://github.com/user-attachments/assets/9cd95fb6-cbb0-4d79-a3a7-2d7e9f0da283)

**Comment by JSKenyon** [comment]
Hmmm, how large is the problem MS? Just wondering if it would be worth trying to get my hands on it. This seems like something really insidious.

**Comment by AKHughes1994** [comment]
It's *only* ~6 GB

**Comment by JSKenyon** [comment]
That isn't horrendous, if there is some convenient way to make it available.

**Comment by AKHughes1994** [comment]
See if this works, 

https://drive.google.com/file/d/1qVnTtN334LTGl6V4KrduT1lsMV_pm6jl/view?usp=sharing

**Comment by JSKenyon** [comment]
Download in progress! Thanks!

**Comment by AKHughes1994** [comment]
@JSKenyon 

I've confirmed some interaction between CASA `mstransform` collapsing the VLA SPWs into a SPW. 

I re-ran the imaging using a msfile split out without the `combinespw=True`

`mstransform(vis = ms, outputvis = split_ms, datacolumn='corrected', field=field, spw=spw)#, combinespws=True)`

and it worked! See imaging proof: 

![image](https://github.com/user-attachments/assets/db6d0660-f9d3-4818-9fa6-0902ef930884)

![image](https://github.com/user-attachments/assets/90329a89-a9fc-4bb0-a46d-db8c5fff701f)

I'm afraid I have no idea **why** this is the case, nor why it doesn't fail for X-band (as the X-band msfile also has `combinespws=True`)

Andrew

**Comment by JSKenyon** [comment]
I also have an update - in the data you sent, the FLAG_ROW column was all set to True. Can you confirm that that was the case?

**Comment by sjperkins** [comment]
> I also have an update - in the data you sent, the FLAG_ROW column was all set to True. Can you confirm that that was the case?

Oh dear, did I respect the specification too much :rofl:

**Comment by JSKenyon** [comment]
> > I also have an update - in the data you sent, the FLAG_ROW column was all set to True. Can you confirm that that was the case?
> 
> Oh dear, did I respect the specification too much 🤣

I don't think so. QuartiCal ors in the FLAG_ROW values. The question is where/when did those values get set? Just want to be sure I know before chasing down @AKHughes1994 problem further.

**Comment by AKHughes1994** [comment]
@JSKenyon 

Yes, I looked at that, and it is true. I also checked, and that isn't the case for the msfile with `combinespws=False.`

I think this is what is going on: The first C-band spectral window is flagged (This is intentional. The data were bad). When `mstransform` collapses the SPWs into a single SPW it appends the first SPW's FLAG_ROW column (which is all True) to the new msfile, and then QC is (rightfully) interpreting the entire SPW as needing to be flagged.  

So it's a CASA issue rather than a QC.... I should have guessed that.

Andrew

**Comment by JSKenyon** [comment]
> @JSKenyon
> 
> Yes, I looked at that, and it is true. I also checked, and that isn't the case for the msfile with `combinespws=False.`
> 
> I think this is what is going on: The first C-band spectral window is flagged (This is intentional. The data were bad). When `mstransform` collapses the SPWs into a single SPW it appends the first SPW's FLAG_ROW column from the original multi-SPW msfile (which is all True) to the new single-SPW msfile, and then QC is (rightfully) interpreting the entire SPW as needing to be flagged.
> 
> So it's a CASA issue rather than a QC.... I should have guessed that.
> 
> Andrew

Ah ok - that makes sense. You have fallen victim of a CASA implementation detail. I guess you could just unset all of FLAG_ROW - the flags in FLAG will probably be sufficient.

**Comment by IanHeywood** [comment]
I have a vague recollection (which may be wrong now, or always has been) that combining SPWs using mstransform does not rewrite the SPECTRAL_WINDOW table in the MS properly to reflect the new structure. Out of interest can you check the number of rows in that table, and also the unique values in the DATA_DESC_ID column of the main table in the transformed MS? Might be some further headaches there...
